# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd6d38ddaf6fc90ae6919fbf08c936bc5dc6a343e3313ac1e90015c05f90e583a51acd5fd6cb1eb8ac597bca10978cc24feb1c0cf4b83675d934ed07d24db878

test:
  secret_key_base: 0d484c1193a5bd8ee05e50556d23c83bef81822731a24753b1a9f52931a72669d576be2135b8199ac8be883ff50a8e1c3445142291b38dd0f9f14c37666dce60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
